# Generated by Django 6.1.1 on 2026-10-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Procedimento / Exame',
                'verbose_name_plural': 'Procedimentos e Exames',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField(verbose_name='Data e Horário')),
                ('local_atendimento', models.CharField(help_text='Ex: UBS Centro, Posto Bairro Sul, Clínica Municipal', max_length=150)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo/Queixa')),
                ('observacoes_medicas', models.TextField(blank=True, null=True, verbose_name='Evolução / Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pessoa.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pessoa.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-data_horario'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Vínculo')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.procedimento')),
            ],
            options={
                'verbose_name': 'Procedimento da Consulta',
                'verbose_name_plural': 'Procedimentos da Consulta',
                'unique_together': {('consulta', 'procedimento')},
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='procedimentos',
            field=models.ManyToManyField(blank=True, help_text='Selecione os exames/procedimentos vinculados a esta consulta', related_name='consultas', through='consulta.ConsultaProcedimento', to='consulta.procedimento'),
        ),
    ]
