# Generated by Django 6.1.1 on 2026-10-05 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-data_consulta'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='procedimento',
            options={'verbose_name': 'Procedimento', 'verbose_name_plural': 'Procedimentos'},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data_horario',
        ),
        migrations.AddField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Consulta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='observacoes_medicas',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='procedimentos',
            field=models.ManyToManyField(blank=True, help_text='Selecione os procedimentos vinculados a esta consulta', related_name='consultas', through='consulta.ConsultaProcedimento', to='consulta.procedimento'),
        ),
    ]
